# fly.toml file generated for code-santa on 2021-11-28T10:33:44-05:00

app = "code-santa"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "/app/entry eval CodeSanta.Release.migrate"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
